channels:
  default: CNBC_TV

fetch:
  period_type: today
  number: 1

summary:
  task: |
    I would like you to summarize the transcript with the following instructions:
    First categorize the video content. The category should be one of the following: Crypto, Macro, Politics, Technology, Small Caps or Other.
    Then summarize the stocks that are mentioned in this video.
    Then provide key takeaways in a bullet point format. Please make sure don't miss anything about small cap, Nvidia, Tesla, Meta and Macro is mentioned in the transcript.
    Please print the summary in a human-readable format like the following:
    Category: Technology
    Stock mentioned: STOCK1, STOCK2, STOCK3
    Key takeaways:
    * takeaway 1
    * takeaway 2
    * takeaway 3

file_operations:
  file_prefix: youtube_analysis
  output_types:
    - csv
    - html
    - txt

email:
  send: true
  recipients:
    - recipient1@example.com
    - recipient2@example.com

stop_on_error: false